### ISSUE TITLE
pymysql error "Could not find first log file name in binary log index file" , what to do now?

### ISSUE THREAD

**Issue by mark-ellul** [the4thdoctor/pg_chameleon#120]
**Describe the bug**
after a few hiccups as reported in #119  I am getting an error after using  "enable_replica" and then "start_replica" with debug reports this error....

2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 MainProcess INFO global_lib.py (608): Checking if the replica for source mysql is stopped 
2020-08-18 15:16:26 MainProcess INFO global_lib.py (618): Cleaning not processed batches for source mysql
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (3238): Cleaning table t_log_replica_mysql_1
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (3238): Cleaning table t_log_replica_mysql_2
2020-08-18 15:16:26 MainProcess INFO global_lib.py (549): Starting the replica daemons for source mysql 
2020-08-18 15:16:26 MainProcess DEBUG global_lib.py (558): Replica process for source mysql is running
2020-08-18 15:16:26 read_replica DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 replay_replica DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:26 MainProcess DEBUG pg_lib.py (1276): Cleaning replayed batches for source mysql older than 1 day
2020-08-18 15:16:26 read_replica DEBUG pg_lib.py (679): There is already a database connection active.
2020-08-18 15:16:26 read_replica DEBUG pg_lib.py (3110): Collecting schema mappings for source mysql
2020-08-18 15:16:26 read_replica DEBUG mysql_lib.py (1411): Batch data [(3346, 'mysql-bin.000014', 64407185, 't_log_replica_mysql_1', '')] 
2020-08-18 15:16:26 read_replica DEBUG mysql_lib.py (959): collecting table type map
2020-08-18 15:16:26 read_replica DEBUG mysql_lib.py (1176): GTID DISABLED - log_file mysql-bin.000014, log_position 64407185. id_batch: 3346 
2020-08-18 15:16:27 MainProcess ERROR global_lib.py (562): Read process alive: False - Replay process alive: True
2020-08-18 15:16:27 MainProcess ERROR global_lib.py (563): Stack trace: Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/pg_chameleon/lib/global_lib.py", line 491, in read_replica
    self.mysql_source.read_replica()
  File "/root/venv/lib/python3.8/site-packages/pg_chameleon/lib/mysql_lib.py", line 1412, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/root/venv/lib/python3.8/site-packages/pg_chameleon/lib/mysql_lib.py", line 1178, in __read_replica_stream
    for binlogevent in my_stream:
  File "/root/venv/lib/python3.8/site-packages/pymysqlreplication/binlogstream.py", line 430, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/root/venv/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/venv/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1236, 'Could not find first log file name in binary log index file')

2020-08-18 15:16:27 MainProcess ERROR global_lib.py (569): Read daemon crashed. Terminating the replay daemon.
2020-08-18 15:16:27 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2020-08-18 15:16:27 MainProcess INFO global_lib.py (594): Replica process for source mysql ended
(venv) root@ubuntu-s-4vcpu-8gb-nyc3-01:~# chameleon show_status
  Source id  Source name    Type    Status    Consistent    Read lag          Last read            Replay lag    Last replay
-----------  -------------  ------  --------  ------------  ----------------  -------------------  ------------  -------------------
          1  mysql          mysql   stopped   Yes           14 days 21:47:15  2020-08-03 17:32:55  00:00:00      2020-08-03 17:32:55

**To Reproduce**
chameleon start_replica --source mysql --config default --debug

**Expected behavior**

Replication should start

**Screenshots**

**Environment(please complete the following information):**
- OS: [e.g. Devuan GNU/Linux]
ubuntu 14.04.1 - source database
ubuntu 20.04.1 LTS replica database

- MySQL Version[e.g. 5.7.27]
version 5.6.33-0ubuntu0.14.04.1-log

- PostgreSQL Version[e.g. 11]
psql (12.2 (Ubuntu 12.2-4))

- Python Version [e.g. 3.5]
Python 3.8.2

- Cloud hosted database [e.g PostgreSQL on AWS RDS and MySQL on Google Cloud]

Postgres ( psql (12.2 (Ubuntu 12.2-4)) ) running on Digital Ocean
MySQL on Digital Ocean

*** configuration with passwords and ips redacted ****
```
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion
# into a different one.

type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"


# postgres  destination connection
pg_conn:
  host: "localhost"
  port: "5432"
  user: "col"
  password: ""
  database: "col"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: ""
      port: "3306"
      user: ""
      password: ""
      charset: 'utf8'
      connect_timeout: 100
    schema_mappings:
      col: col
    limit_tables:
    skip_tables:
            - col.audit_logs
    grant_select_to:
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 10000
    replay_max_rows: 1000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: false
    type: mysql
    skip_events:
      insert:
        - delphis_mediterranea.foo  # skips inserts on delphis_mediterranea.foo
      delete:
        - delphis_mediterranea  # skips deletes on schema delphis_mediterranea
      update:
    keep_existing_schema: No
```

**Additional context**
As you can see from the show_status response above, the read lag was for 2 weeks (while I was away). Could the fact that the read from mysql was so old, that the replica files were removed?

What should I do to reset the replica? or re-build it? or whatever?
