### ISSUE TITLE
Error starting replication from MySQL in Mac

### ISSUE THREAD

**Issue by Davidrodrguez98** [the4thdoctor/pg_chameleon#176]
**Describe the bug**
There is an error executing `chameleon start_replica --config default --source mysql --debug`. The error is `TypeError: cannot pickle 'weakref.ReferenceType' object` and when I run `chameleon show_status --source mysql` the status is `initialised`.

When I run just `chameleon start_replica --config default --source mysql` it shows the message `Starting the replica process for source mysql`, but status is still `initialised` and when I delete a row in source it is not replicating in destination.

The first copy of the table is completed properly but changes are not replicating.

**To Reproduce**
- `chameleon create_replica_schema --debug`
- `chameleon add_source --config default --source mysql --debug`
- `chameleon init_replica --config default --source mysql --debug`
- `chameleon start_replica --config default --source mysql --debug`

~/.pg_chameleon/configuration/default.yml:
```
---
# global settings
pid_dir: "~/.pg_chameleon/pid/"
log_dir: "~/.pg_chameleon/logs/"
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ""
rollbar_env: ""

# type_override allows the user to override the default type conversion
# into a different one.

type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

# postgres  destination connection
pg_conn:
  host: "host"
  port: "port"
  user: "usr_replica"
  password: "pass"
  database: "database_replica"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "host"
      port: "port"
      user: "usr_replica"
      password: "pass"
      charset: "utf8"
      connect_timeout: 10
    schema_mappings:
      schema-source: schema_dest
    limit_tables:
      - schema-source.Table
    skip_tables:
    grant_select_to:
      - usr_readonly
    lock_timeout: "500s"
    my_server_id: 201801222
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: "1 day"
    copy_max_memory: "300M"
    copy_mode: "file"
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    type: mysql
```
**Expected behavior**
I am expecting after the command `chameleon start_replica --config default --source mysql --debug` all changes performed in source are replicated in destination.

**Screenshots**
![Captura de pantalla 2025-01-15 a las 13 37 43](https://github.com/user-attachments/assets/e7a53c0a-8df1-419c-869f-2dbac7331de2)

**Environment(please complete the following information):**
 - OS: MacOS Sequoia 15.2
 - MySQL Version 8.0
 - PostgreSQL Version 17
 - Python Version 3.11
 - Cloud hosted database PostgreSQL on Google Cloud and MySQL on Google Cloud
