### ISSUE TITLE
MySQL numeric password breaks pg_chameleon

### ISSUE THREAD

**Issue by lifeboy** [the4thdoctor/pg_chameleon#31]
When using a numeric password in the config file, a python error "_AttributeError: 'int' object has no attribute 'encode'_" occurs when running ./chameleon.py create_schema.
```
mysql_conn:
    host: hout1
    port: 3306
    user: mysql_rep
    passwd: 123456
```
A workaround is to enclose the password with double quotes -> "".
```
    passwd: "123456"
```
