### ISSUE TITLE
Sync tables doesn't work?

### ISSUE THREAD

**Issue by Hoya** [the4thdoctor/pg_chameleon#65]
I'm trying to setup a new replication to a Postgres target from an existing MySQL source with a fair amount of data (200GB~300GB).

I've been able to setup and get the replication running and confirm it's working as I can see new tables that have been added on the MySQL source also show up on the Postgres target.

However, I can't seem to figure out how to sync all of the existing table structures and data so that the source and target are in sync. I've tried the refresh_schema and sync_tables commands but nothing seems to change. When I check the source status I just notice "Status = synced" and that's about it, none of the tables are copied over.

Any help would be appreciated thanks.

**Comment by the4thdoctor** [comment]
Hi, can you please post the debug log of the process? You can get it just adding - - debug to the command line.
Thanks

**Comment by Hoya** [comment]
I tried syncing just 1 table and the output is as below:

`(venv) root@workspace:~/.pg_chameleon/configuration# chameleon sync_tables --config default --source mysql --tables soomgo.auth_user --debug
2018-03-21 19:53:30 MainProcess DEBUG pg_lib.py (614): Changing the autocommit flag to True
2018-03-21 19:53:30 MainProcess DEBUG pg_lib.py (614): Changing the autocommit flag to True
2018-03-21 19:53:30 MainProcess INFO mysql_lib.py (768): Starting sync tables for source mysql
2018-03-21 19:53:30 MainProcess DEBUG pg_lib.py (614): Changing the autocommit flag to True
2018-03-21 19:53:30 MainProcess DEBUG pg_lib.py (2676): Collecting schema mappings for source mysql
2018-03-21 19:53:31 MainProcess DEBUG mysql_lib.py (777): The tables affected are soomgo.auth_user
2018-03-21 19:53:31 MainProcess DEBUG mysql_lib.py (233): Creating the schema _soomgo_load_tmp.
2018-03-21 19:53:31 MainProcess DEBUG mysql_lib.py (235): Creating the schema soomgo_load.
2018-03-21 19:53:31 MainProcess DEBUG pg_lib.py (614): Changing the autocommit flag to False
2018-03-21 19:53:31 MainProcess DEBUG pg_lib.py (614): Changing the autocommit flag to True
2018-03-21 19:53:31 MainProcess DEBUG mysql_lib.py (246): Dropping the schema _soomgo_load_tmp.
2018-03-21 19:53:31 MainProcess DEBUG pg_lib.py (652): Changing the lock timeout for the session to 120s.
2018-03-21 19:53:31 MainProcess INFO pg_lib.py (2916): Set high watermark for source: mysql
2018-03-21 19:53:31 MainProcess ERROR global_lib.py (55): Could not send the message to rollbar.
2018-03-21 19:53:31 MainProcess INFO mysql_lib.py (798): the sync for tables soomgo.auth_user in source mysql is complete`

**Comment by the4thdoctor** [comment]
it looks to me that this table is excluded for some ways.
I would first check if is listed in `skip_tables` or not included in `limit_tables`.

If all looks fine I would check if the replica user can select from that table.

**Comment by Hoya** [comment]
Here's the output you requested:

```
  Source id  Source name    Type    Status       Consistent    Read lag    Last read    Replay lag    Last replay
-----------  -------------  ------  -----------  ------------  ----------  -----------  ------------  -------------
          3  mysql          mysql   initialised  No            N/A                      N/A

== Schema mappings ==
Origin schema    Destination schema
---------------  --------------------
soomgo           soomgo_blah
sgforce          sgforce_blah

== Replica status ==
---------------------  -
Tables not replicated  0
Tables replicated      0
All tables             0
Replayed rows
Replayed DDL
Skipped rows
---------------------  -
```

Nothing really happening.

Also, my skip_tables and limit_tables are empty:


```
sources:
    mysql:
        db_conn:
            host: "***********"
            port: "3306"
            user: "***********"
            password: "***********"
            charset: 'utf8'
            connect_timeout: 10
        schema_mappings:
            A: A-a
            B: B-b
        lock_timeout: "120s"
        my_server_id: 7905
        grant_select_to:
        limit_tables:
        skip_tables:
        replica_batch_size: 100000
        replay_max_rows: 100000
        batch_retention: '1 day'
        copy_max_memory: "1000M"
        copy_mode: 'direct'  
        out_dir: /tmp
        sleep_loop: 1
        on_error_replay: continue
        type: mysql
```
