### ISSUE TITLE
NULL instead of DEFAULT value in migration

### ISSUE THREAD

**Issue by Sahaquielxo** [the4thdoctor/pg_chameleon#74]
Hi, I have a table in MySQL with:   

```
`last_update` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
```

 but when the default value is used in MySQL, pg_chameleon rewrite it as Null, so get an error:

> 2018-05-14 14:07:45 MainProcess ERROR pg_lib.py (3406): SQLCODE: 23502 SQLERROR: ERROR:  null value in column "last_update" violates not-null constraint
> DETAIL:  Failing row contains (306238, http://example.com, 0, example, 3093, 3, PHY, 1, Test text, example@example.com, , null, , null, 2002-01-17 18:47:39, 2002-01-17 18:47:39, null, null, 0, , , , 0, 1, 0, 0, 1, 0, null, 0, null, null).

The real data:

```
mysql> SELECT * FROM account WHERE id='306238'\G
*************************** 1. row ***************************
               id: 306238
              url: http://example.com
        parent_id: 0
           passwd: example
            flags: 3093
              gif: 3
          orgtype: PHY
              grp: 1
             name: Test text
             addr: example@example.com
        alt_title:
     announce_url: NULL
   announce_title:
         add_year: NULL
       start_time: 2002-01-17 18:47:39
       reset_time: 2002-01-17 18:47:39
      rateon_time: NULL
     rateoff_time: NULL
      start_count: 0
         keywords:
            owner:
          creator:
            alive: 0
     user_deleted: 1
          in_rate: 0
              rss: 0
          quality: 1
     announce_rss: 0
          favicon: NULL
     days_wo_stat: 0
dismiss_reason_id: NULL
      last_update: 0000-00-00 00:00:00
1 row in set (0.00 sec)
```

Can you help me with that? If there a way to fix an error?
