### ISSUE TITLE
Cannot initialize replication

### ISSUE THREAD

**Issue by gpetepg** [the4thdoctor/pg_chameleon#96]
I am unable to transfer any data without getting this issue. I made sure to configure MySQL's my.cnf and restart it as well.

    table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()] KeyError: 
    'table_name'

I've tried variations of the database names in the configuration nothing seems to work. My localhost Postgres desired table is to output is public.testing and the MySQL schema is testing

Which I believe should look like this:

    pg_conn:
      host: "localhost"
      port: "5432"
      user: "usr_replica"
      password: ""
      database: "testing"
      charset: "utf8"

    sources:
      mysql:
        db_conn:
          host: "localhost"
          port: "3306"
          user: "usr_replica"
          password: ""
          charset: 'utf8'
          connect_timeout: 10
        schema_mappings:
          testing: public

Here is the full stacktrace.

    Traceback (most recent call last):
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/bin/chameleon", line 5, in     <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/bin/chameleon.py", line 58, in     <module>
        getattr(replica, args.command)()
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/lib/python3.6/site-    packages/pg_chameleon/lib/global_lib.py", line 327, in init_replica
        self.__init_mysql_replica()
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/lib/python3.6/site-    packages/pg_chameleon/lib/global_lib.py", line 337, in __init_mysql_replica
        self.mysql_source.init_replica()
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/lib/python3.6/site-    packages/pg_chameleon/lib/mysql_lib.py", line 1374, in init_replica
        self.get_table_list()
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/lib/python3.6/site-    packages/pg_chameleon/lib/mysql_lib.py", line 261, in get_table_list
        table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()]
      File "/Users/tylerguo/Documents/HTRepos/ht-processdb/ve/lib/python3.6/site-    packages/pg_chameleon/lib/mysql_lib.py", line 261, in <listcomp>
        table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()]
    KeyError: 'table_name'

**Comment by the4thdoctor** [comment]
Mmm does the user have access to the tables? There are specify grants to give before being able to use pgchameleon

**Comment by the4thdoctor** [comment]
Schema mappings seems wrong to me. What's the database on mysql you are reading from?

**Comment by gpetepg** [comment]
>Mmm does the user have access to the tables? There are specify grants to give before being able to use pgchameleon

Yes, I made sure to log in and have even gotten a stacktrace when an incorrect password was given.

> Schema mappings seems wrong to me. What's the database on mysql you are reading from?

I tried using my own schema/database at first as well as my own credentials after that didn't work I followed one of your talks on YouTube and used the Sakila database and your example credentials.

MySQL version 8.0.12 and Postgres version 11.2 on macOS High Sierra 10.13.3

**Comment by nawazahmed1** [comment]
i got the same issue with PostgreSQL 11.3, MySQL 8.0.16 (community version), pg-chameleon 2.0.10 on CentOS Linux release 7.6.1810. Here is my my.cnf and defaults.yml. I have followed the online documentation with some addition references from Google.

**cat /etc/my.cnf**
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
#
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
#
#system timestamp
log_timestamps=SYSTEM
binlog_format= ROW
binlog_row_image=FULL
log-bin = mysql-bin
server-id = 1

**cat default.yml**
---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion into a different one.
type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

#postgres  destination connection
pg_conn:
  host: "localhost"
  port: "5432"
  user: "usr_replica"
  password: "replica"
  database: "db_replica"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "localhost"
      port: "3306"
      user: "usr_replica"
      password: "replica123"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      world_x: pgworld_x
    limit_tables:
#      - delphis_mediterranea.foo
    skip_tables:
#      - delphis_mediterranea.bar
    grant_select_to:
      - usr_replica
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql
    skip_events:
      insert:
#        - delphis_mediterranea.foo #skips inserts on the table delphis_mediterranea.foo
      delete:
#        - delphis_mediterranea #skips deletes on schema delphis_mediterranea
      update:


  pgsql:
  db_conn:
    host: "localhost"
    port: "5432"
    user: "usr_replica"
    password: "replica"
    database:  "db_replica"
    charset: 'utf8'
    connect_timeout: 10
#      schema_mappings:
#        world_x: pg_world_x
#      limit_tables:
#        - loxodonta_africana.foo
#      skip_tables:
#        - loxodonta_africana.bar
#      copy_max_memory: "300M"
#      grant_select_to:
#        - usr_readonly
#      lock_timeout: "10s"
#      my_server_id: 100
#      replica_batch_size: 3000
#      replay_max_rows : 10000
#      sleep_loop: 5
#      batch_retention: '1 day'
#      copy_mode: 'file'
#      out_dir: /tmp
#      type: pgsql

**Comment by nawazahmed1** [comment]
i got the same issue with PostgreSQL 11.3, MySQL 8.0.16 (community version), pg-chameleon 2.0.10 on CentOS Linux release 7.6.1810. Here is my my.cnf and defaults.yml. I have followed the online documentation with some addition references from Google.

```
 cat default.yml
---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion into a different one.
type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"




#postgres  destination connection
pg_conn:
  host: "localhost"
  port: "5432"
  user: "usr_replica"
  password: "replica"
  database: "db_replica"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "localhost"
      port: "3306"
      user: "usr_replica"
      password: "replica123"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      world_x: pgworld_x
    limit_tables:
#      - delphis_mediterranea.foo
    skip_tables:
#      - delphis_mediterranea.bar
    grant_select_to:
      - usr_replica
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql
    skip_events:
      insert:
#        - delphis_mediterranea.foo #skips inserts on the table delphis_mediterranea.foo
      delete:
#        - delphis_mediterranea #skips deletes on schema delphis_mediterranea
      update:


  pgsql:
  db_conn:
    host: "localhost"
    port: "5432"
    user: "usr_replica"
    password: "replica"
    database:  "db_replica"
    charset: 'utf8'
    connect_timeout: 10
#      schema_mappings:
#        world_x: pg_world_x
#      limit_tables:
#        - loxodonta_africana.foo
#      skip_tables:
#        - loxodonta_africana.bar
#      copy_max_memory: "300M"
#      grant_select_to:
#        - usr_readonly
#      lock_timeout: "10s"
#      my_server_id: 100
#      replica_batch_size: 3000
#      replay_max_rows : 10000
#      sleep_loop: 5
#      batch_retention: '1 day'
#      copy_mode: 'file'
#      out_dir: /tmp
#      type: pgsql
```

```
cat /etc/my.cnf
# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/8.0/en/server-configuration-defaults.html

[mysqld]
#
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
#
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
#
#system timestamp
log_timestamps=SYSTEM
binlog_format= ROW
binlog_row_image=FULL
log-bin = mysql-bin
server-id = 1


```

**Comment by nawazahmed1** [comment]
I think i kind of figured out what's happening but i need the developer to confirm if my analysis was right and the fix for that.

I could see the below code in the mysql_lib.py, but just a few line above that code is a sql query (pasted further below), which gets a list of tables that belong to the intended schema. I tried running that plain sql against the MySQL database and i get the results just fine but there is a header row "TABLE_NAME", which i assume is getting processed through the code of the for loop "for schema in self.schema_list:".

I tried to include that header as a table name in the "skip tables" section but to no avail. I still get the same error.

`"table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()]" `


```
sql_tables="""
			SELECT 
				table_name
			FROM 
				information_schema.TABLES 
			WHERE 
					table_type='BASE TABLE' 
				AND table_schema=%s
```

**Comment by the4thdoctor** [comment]
sorry for the long delay, I've been around. I'll pick up all the stuff and the project's development asap.

**Comment by sunbing81** [comment]
> 
> ... There is a header row "TABLE_NAME", which i assume is getting processed through the code of the for loop "for schema in 

As pointed in the above comment, the cursor returns a dict in which the key is "TABLE_NAME" (all upper case), so change the key 'table_name' in [line](https://github.com/the4thdoctor/pg_chameleon/blob/118f3589bb0f07da329ed8b691f0f33fa71a679d/pg_chameleon/lib/mysql_lib.py#L261) to 'TABLE_NAME' will be an immediate fix.

**Comment by sunbing81** [comment]
Fine, there are similar cases all over mysql_lib.py. Changing the lower case "table_name" (and alike) to "TABLE_NAME" may have compatibility issues with previous mysql version.

I think maybe we can change the query statement:
```sql
SELECT
	table_name
FROM
	information_schema.TABLES
WHERE
	table_type='BASE TABLE'
	AND table_schema=%s
;
```

to something like:
```sql
SELECT
	table_name AS table_name
FROM
	information_schema.TABLES
WHERE
	table_type='BASE TABLE'
	AND table_schema=%s
;
```

Works for me (MySQL 8.0)

**Comment by the4thdoctor** [comment]
thanks, I'll have a look

**Comment by jeremydesvals** [comment]
Hi, i got the same issue, version :
mysql  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL)
psql (PostgreSQL) 9.6.15
CentOS Linux release 7.7.1908 (Core)

---
content of default.yml :
```
# global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''# type_override allows the user to override the default type conversion
# into a different one.type_override:
 "tinyint(1)":
   override_to: boolean
   override_tables:
     - "*"# postgres  destination connection
pg_conn:
 host: "localhost"
 port: "5432"
 user: "usr_replica"
 password: "pass"
 database: "db_replica"
 charset: "utf8"sources:
 mysql:
   db_conn:
     host: "localhost"
     port: "3306"
     user: "usr_replica"
     password: "pass"
     charset: 'utf8'
     connect_timeout: 10
   schema_mappings:
     database: pg_database
   limit_tables:
#      - delphis_mediterranea.foo
   skip_tables:
#      - delphis_mediterranea.bar
   grant_select_to:
     - usr_replica
   lock_timeout: "120s"
   my_server_id: 100
   replica_batch_size: 10000
   replay_max_rows: 10000
   batch_retention: '1 day'
   copy_max_memory: "300M"
   copy_mode: 'file'
   out_dir: /tmp
   sleep_loop: 1
   on_error_replay: continue
   on_error_read: continue
   auto_maintenance: "disabled"
        gtid_enable: false
   type: mysql
   skip_events:
     insert:
#        - delphis_mediterranea.foo  # skips inserts on delphis_mediterranea.foo
     delete:
#        - delphis_mediterranea  # skips deletes on schema delphis_mediterranea
     update:#  pgsql:
#    db_conn:
#      host: "localhost"
#      port: "5432"
#      user: "usr_replica"
#      password: "never_commit_passwords"
#      database: "db_replica"
#      charset: 'utf8'
#      connect_timeout: 10
#      schema_mappings:
#        loxodonta_africana: elephas_maximus
#      limit_tables:
#        - loxodonta_africana.foo
#      skip_tables:
#        - loxodonta_africana.bar
#      copy_max_memory: "300M"
#      grant_select_to:
#        - usr_readonly
#      lock_timeout: "10s"
#      my_server_id: 100
#      replica_batch_size: 3000
#      replay_max_rows: 10000
#      sleep_loop: 5
#      batch_retention: '1 day'
#      copy_mode: 'file'
#      out_dir: /tmp
#      type: pgsql
```

```
# chameleon init_replica --config default --debug --source mysql
2019-11-07 09:56:39 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 09:56:39 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 09:56:39 MainProcess DEBUG mysql_lib.py (1366): starting init replica for source mysql
2019-11-07 09:56:39 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 09:56:39 MainProcess DEBUG pg_lib.py (3070): Collecting schema mappings for source mysql
2019-11-07 09:56:39 MainProcess INFO pg_lib.py (1846): deleting all the table references from the replica catalog for source mysql
Traceback (most recent call last):
 File "/root/migration/bin/chameleon", line 5, in <module>
   exec(compile(open(__file__).read(), __file__, 'exec'))
 File "/root/migration/bin/chameleon.py", line 58, in <module>
   getattr(replica, args.command)()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 327, in init_replica
   self.__init_mysql_replica()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 337, in __init_mysql_replica
   self.mysql_source.init_replica()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1374, in init_replica
   self.get_table_list()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 261, in get_table_list
   table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()]
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 261, in <listcomp>
   table_list = [table["table_name"] for table in self.cursor_buffered.fetchall()]
KeyError: 'table_name'
```
After doing the solution from sunbing81 's answer we got this :

```
# chameleon init_replica --config default --debug --source mysql
2019-11-07 10:05:22 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 10:05:22 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 10:05:22 MainProcess DEBUG mysql_lib.py (1366): starting init replica for source mysql
2019-11-07 10:05:22 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2019-11-07 10:05:22 MainProcess DEBUG pg_lib.py (3070): Collecting schema mappings for source mysql
2019-11-07 10:05:22 MainProcess INFO pg_lib.py (1846): deleting all the table references from the replica catalog for source mysql
2019-11-07 10:05:22 MainProcess DEBUG mysql_lib.py (291): Creating the schema _redmine_adm_tmp.
2019-11-07 10:05:22 MainProcess DEBUG mysql_lib.py (293): Creating the schema redmine_adm.
2019-11-07 10:05:22 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _redmine_adm_tmp.
2019-11-07 10:05:22 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 120s.
2019-11-07 10:05:22 MainProcess CRITICAL mysql_lib.py (1400): init replica for source mysql failed
Traceback (most recent call last):
 File "/root/migration/bin/chameleon", line 5, in <module>
   exec(compile(open(__file__).read(), __file__, 'exec'))
 File "/root/migration/bin/chameleon.py", line 58, in <module>
   getattr(replica, args.command)()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 327, in init_replica
   self.__init_mysql_replica()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 337, in __init_mysql_replica
   self.mysql_source.init_replica()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1379, in init_replica
   self.create_destination_tables()
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 394, in create_destination_tables
   self.pg_engine.create_table(table_metadata, table, schema, 'mysql')
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/pg_lib.py", line 2972, in create_table
   table_ddl = self.__build_create_table_mysql( table_metadata,table_name,  schema)
 File "/root/migration/lib64/python3.6/site-packages/pg_chameleon/lib/pg_lib.py", line 2378, in __build_create_table_mysql
   if column["is_nullable"]=="NO":
KeyError: 'is_nullable'
```

Thanks for the help
