### ISSUE TITLE
AttributeError: 'pg_engine' object has no attribute 'pgsql_cur'

### ISSUE THREAD

**Issue by stereobooster** [the4thdoctor/pg_chameleon#98]
Hi there!

I'm trying to configure replica from MySQL to Postgres with docker-compose. I created two db images and separate image for chameleon 

```Dockerfile
FROM python:3.7-alpine

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 pip install pg_chameleon --no-cache-dir && \
 apk --purge del .build-deps && \
 chameleon set_configuration_files

COPY wait-for.sh /bin
VOLUME /root/.pg_chameleon

ENTRYPOINT sh -c '/bin/wait-for.sh db:3306 -- /bin/wait-for.sh pg:5432 -- chameleon init_replica --config default --source mysql --debug'
```

When I run it I get this error: `AttributeError: 'pg_engine' object has no attribute 'pgsql_cur'`.

My guess is that I need to install chameleon inside Postgres image instead of separate image. Do you have any instructions/advices on how to use chameleon with Docker?

Source code is here https://github.com/stereobooster/headless-cms-comparison/tree/master/directus-chameleon-hasura

**Comment by the4thdoctor** [comment]
the error means the connection to postgresql is not successfuly. did you enable postgres to accept the connections from other hosts? what the postgresql log says?

**Comment by mbrgm** [comment]
@stereobooster I had the same issue and from the repo you linked it appears to be for identical reasons:

```
  File "/usr/local/lib/python3.7/site-packages/pg_chameleon/lib/global_lib.py", line 115, in __init__
    self.pg_engine.type_override = self.config["type_override"]
KeyError: 'type_override'
```
It appears to me that you have to specify an empty list in the yaml file when you do not want to have `type override`. The same goes for `limit_tables`, `skip_tables` and `grant_select_to`.

@the4thdoctor Maybe a check for the key or retrieval of the key with a default value on nonexistence would help avoid this kind of error?

**Comment by szcc** [comment]
@the4thdoctor 
Hi there!

I'm trying to configure replica from MySQL to Postgres. 
"chameleon add_source --config default  --debug"
I got error:
"You must specify a source name with the argument --source"
I thought my source already in the default config file ???

**Comment by szcc** [comment]
I updated the config file correct the schema mapping and it works

**Comment by cjrutherford** [comment]
I'm actually having the same issue, and I've tried it with the empty dicts, but nothing. I think it may be related to how the source schema in the schema mappings needs to be escaped (contains a `-`)

How would one properly escape that?

**Comment by the4thdoctor** [comment]
can you provide an example for your schema_mappings?
I'll try to reproduce the issue.
Thanks

**Comment by cjrutherford** [comment]
I want everything in the database, so I just put it in as 
```
    schema_mappings:
      miner-hosting: miner_hosting
    limit_tables: {}
    skip_tables: {}
    grant_select_to:
      - usr_readonly
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: false
    type: mysql
    skip_events: {}
    keep_existing_schema: Yes
```

I read earlier if I wanted to not have limits and skips, to provide an empty dictionary.
